create or replace TABLE ORDER_SUMMARY (
	ID NUMBER(38,0) autoincrement start 1 increment 1 order,
	ITEMS_SOLD_COUNT NUMBER(38,0),
	GUEST_COUNT NUMBER(38,0),
	SUBTOTAL NUMBER(36,4),
	TAX NUMBER(36,4),
	TOTAL NUMBER(36,4),
	LOCATION_ID NUMBER(38,0),
	ADDED_AT TIMESTAMP_TZ(9)
);