create or replace task TASK_DAG_DATASHARE_CRAFTABLE_LOAD_TABLES
	warehouse=HOSPENG_SMALL_WH
	schedule='USING CRON 0 6 * * * America/Chicago'
	USER_TASK_TIMEOUT_MS=3600000
	as CALL dataadmin.SP_DAG_DATASHARE_CRAFTABLE_LOAD_TABLES();