create or replace task TASK_DQ_ACCELERATION_ELEGIBLE
	warehouse=HOSPENG_SMALL_WH
	schedule='USING CRON 0 6 * * 1 America/Chicago'
	USER_TASK_TIMEOUT_MS=3600000
	as CALL DATAADMIN.SP_DQ_ACCELERATION_ELEGIBLE();