CREATE OR REPLACE TABLE DEV_HOSPENG_REPORTING.GIT_TEST.PRODUCTS (
    PRODUCT_ID INT AUTOINCREMENT,
    PRODUCT_NAME STRING,
    PRICE NUMBER(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- SAMPLE DATA
INSERT INTO DEV_HOSPENG_REPORTING.GIT_TEST.PRODUCTS (PRODUCT_NAME, PRICE) VALUES
    ('LAPTOP', 999.99),
    ('PHONE', 150.99),
    ('KEYBOARD', 79.99),
    ('MONITOR', 299.99),
    ('MOUSE', 39.99);