CREATE OR REPLACE PROCEDURE "SP_DATAWAREHOUSECLONE"()
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE 
    SQLTEXT resultset:=(CREATE OR REPLACE SCHEMA DATAWAREHOUSE_TEMP CLONE DATAWAREHOUSE);
BEGIN
   RETURN TABLE(SQLTEXT);
END';