CREATE OR REPLACE PROCEDURE "SP_DATAWAREHOUSERENAME"()
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE 
    SQLTEXT1 resultset:= (DROP SCHEMA IF EXISTS DATAWAREHOUSE_HOLD);
    SQLTEXT2 resultset:= (ALTER SCHEMA DATAWAREHOUSE RENAME TO DATAWAREHOUSE_HOLD);
    SQLTEXT3 resultset:= (ALTER SCHEMA DATAWAREHOUSE_TEMP RENAME TO DATAWAREHOUSE);
BEGIN
   RETURN TABLE(SQLTEXT1);
   RETURN TABLE(SQLTEXT2);
   RETURN TABLE(SQLTEXT3);
END';