CREATE OR REPLACE PROCEDURE "SP_LOAD_AVERO_GETLOCATIONS"()
RETURNS TABLE ("LOCATIONID" NUMBER(38,0), "AVEROLOCATIONID" NUMBER(38,0))
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  res RESULTSET;
BEGIN
  res := (SELECT DISTINCT
        f.VALUE:locationId::INT AS locationId,
        f.VALUE:averoLocationId::INT AS averoLocationId
    FROM
        DATAWAREHOUSE.INTEGRATIONTYPE_DIM IND
    INNER JOIN
        DATAWAREHOUSE.CONFIG_DIM CFD
        ON IND.INTEGRATIONTYPE_DIM_NK = CFD.INTEGRATIONTYPE_DIM_FK
        AND CFD.DW_ISCURRENTROW
        AND IND.DW_ISCURRENTROW
        AND NOT IND.DW_ISDELETED
        AND IND.INTEGRATIONTYPE = ''averoSFTP'',
    LATERAL FLATTEN(input => PARSE_JSON(CFD.config):locations) f);
  RETURN TABLE(res);
END;
';