CREATE OR REPLACE PROCEDURE "SP_LOADSTAGETABLES_ALL"()
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE 
    SQLStmt resultset;
    SQLMessage resultset := (SELECT ''Stage load comlete.'' );
--========================================================================================================
--Get all of the Load Sprocs
--========================================================================================================
-- --Put all of the sprocs into a list
-- drop table proclist;
-- SHOW PROCEDURES;

-- CREATE TEMP TABLE proclist AS
--      SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- select * from proclist;

-- SELECT ''CALL '' || "schema_name" || ''.'' || "name" || ''(TRUE);'' as sqltext
--   FROM proclist
-- WHERE "schema_name" = ''DATAADMIN''
--   AND "name" ilike ''SP_STAGELOAD%''
--   AND "name" not ilike ''%ERROR%''
-- ;

  -- CALL DATAADMIN.SP_STAGELOADCASHPAYMENTLEDGER_FACT(TRUE);
  -- TRUNCATE TABLE DATAWAREHOUSE_TEMP.CASHPAYMENTLEDGER_FACT;
  --SELECT COUNT(*) FROM DATAADMIN.ADDRESS_DIM;   --1850
   --SELECT COUNT(*) FROM DATAWAREHOUSE_TEMP.ADDRESS_DIM; 
    -- TRUNCATE TABLE DATAWAREHOUSE_TEMP.ADDRESS_DIM;
 ----------------------------------------------------------------------------------------------------------- 
BEGIN 

CALL DATAADMIN.SP_STAGELOADACTIVITY_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADADDRESS_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADBATCH_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADCASHBANKEVENT_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADCASHBANK_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADCASHPAYMENTLEDGER_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADCCTRANSACTION_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADCHECKCASHPAYMENTLEDGER_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADCHEQUE_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADCLOSEOUTSUMMARY_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADCOGSCATEGORY_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADDAYPART_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADDAYPARTSCHEDULE_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADDISCOUNTCHECK_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADDISCOUNTITEM_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADDISCOUNTREASON_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADDRAWER_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADEMPLOYEE_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADEMPLOYMENTPERIOD_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADFEETAX_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADTAX_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADGIFTCARDACTIVITY_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADGIFTCARDTRANSACTION_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADGIFTCARD_DIM(TRUE);


CALL DATAADMIN.SP_STAGELOADITEM_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADJOBPOSITION_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADLOCATIONGROUP_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADLOCATION_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADLOCATION_LOCATIONGROUP_XREF(TRUE);
CALL DATAADMIN.SP_STAGELOADMENUGROUP_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADMENUITEMNAME_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADMENUITEM_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADMENUITEM_MENUGROUP_XREF(TRUE);

CALL DATAADMIN.SP_STAGELOADINTEGRATIONTYPE_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADINTEGRATION_FACT(TRUE);

CALL DATAADMIN.SP_STAGELOADITEMMODIFIER_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADMERCHANT_ORGANIZATION_XREF(TRUE);
CALL DATAADMIN.SP_STAGELOADMERCHANT_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADMODIFIER_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADMODIFIEROPTIONS_DIM(TRUE);


CALL DATAADMIN.SP_STAGELOADORDERTYPE_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADORGANIZATION_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADOVERTIMELABORRULE_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADOVERTIMELABORRULE_JOBPOSITION_XREF(TRUE);
CALL DATAADMIN.SP_STAGELOADPAYINOUT_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADPAYINPAYOUTREASON_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADPAYMENTMETHOD_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADPAYMENTS_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADPHONENUMBER_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADREFUNDS_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADREPORTCATEGORY_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADREVENUECENTER_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADSHIFTBREAK_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADSHIFT_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADSTANDARDDISCOUNT_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADSURCHARGE_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADSURCHARGE_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADTAXASSOCIATION_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADTAXASSOCIATION_MENUITEM_XREF(TRUE);
CALL DATAADMIN.SP_STAGELOADTAXRATE_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADTAXSETTINGS_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADTAX_FACT(TRUE);
CALL DATAADMIN.SP_STAGELOADTERMINAL_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADVARIANT_DIM(TRUE);
CALL DATAADMIN.SP_STAGELOADVOIDREASON_DIM(TRUE);


    RETURN TABLE(SQLMessage);

END';