CREATE OR REPLACE PROCEDURE "SP_STAGELOADTAXSETTINGS_DIM"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.TAXSETTINGS_DIM),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.TAXSETTINGS_DIM(   
          TAXSETTINGS_DIM_NK, 
          TAXSETTINGS_ID, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          LOCATION_DIM_FK, 
          LOCATIONGROUP_DIM_FK, 
          TRACK_TAXES_ON_COMPS, 
          CREATED_AT, 
          UPDATED_AT, 
          TAX_TRACKING, 
          RECEIPT_OPTIONS, 
          ROUNDING_METHOD, 
          COMBINED_RECEIPT_NAME 
) 
 SELECT   TAXSETTINGS_DIM_NK  as   TAXSETTINGS_DIM_NK,  
   TAXSETTINGS_ID  as   TAXSETTINGS_ID,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   LOCATION_DIM_FK  as   LOCATION_DIM_FK,  
   LOCATIONGROUP_DIM_FK  as   LOCATIONGROUP_DIM_FK,  
   TRACK_TAXES_ON_COMPS  as   TRACK_TAXES_ON_COMPS,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   TAX_TRACKING  as   TAX_TRACKING,  
   RECEIPT_OPTIONS  as   RECEIPT_OPTIONS,  
   ROUNDING_METHOD  as   ROUNDING_METHOD,  
   COMBINED_RECEIPT_NAME  as   COMBINED_RECEIPT_NAME 
  FROM DATAADMIN.TAXSETTINGS_DIM
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''TAXSETTINGS_DIM'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''TAXSETTINGS_DIM'',''COUNT''));
END IF;
return table(errorCount_res); END';