CREATE OR REPLACE PROCEDURE "SP_STAGELOADJOBPOSITION_DIM"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.JOBPOSITION_DIM),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.JOBPOSITION_DIM(   
          JOBPOSITION_DIM_NK, 
          JOB_POSITION, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          JOBCATEGORY_DIM_FK, 
          ORGANIZATION_DIM_FK, 
          IS_ARCHIVED, 
          IS_CASH_DRAWER_ASSIGNMENT_REQUIRED, 
          IS_TRAINING, 
          HAS_SKIP_AUTO_CLOCKOUT, 
          CREATED_AT, 
          UPDATED_AT, 
          ARCHIVED_AT, 
          DEFAULT_PAY_RATE 
) 
 SELECT   JOBPOSITION_DIM_NK  as   JOBPOSITION_DIM_NK,  
   JOB_POSITION  as   JOB_POSITION,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   JOBCATEGORY_DIM_FK  as   JOBCATEGORY_DIM_FK,  
   ORGANIZATION_DIM_FK  as   ORGANIZATION_DIM_FK,  
   IS_ARCHIVED  as   IS_ARCHIVED,  
   IS_CASH_DRAWER_ASSIGNMENT_REQUIRED  as   IS_CASH_DRAWER_ASSIGNMENT_REQUIRED,  
   IS_TRAINING  as   IS_TRAINING,  
   HAS_SKIP_AUTO_CLOCKOUT  as   HAS_SKIP_AUTO_CLOCKOUT,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   ARCHIVED_AT  as   ARCHIVED_AT,  
   DEFAULT_PAY_RATE  as   DEFAULT_PAY_RATE 
  FROM DATAADMIN.JOBPOSITION_DIM
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''JOBPOSITION_DIM'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''JOBPOSITION_DIM'',''COUNT''));
END IF;
return table(errorCount_res); END';