CREATE OR REPLACE PROCEDURE "SP_STAGELOADITEMMODIFIER_DIM"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.ITEMMODIFIER_DIM),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.ITEMMODIFIER_DIM(   
          ITEMMODIFIER_DIM_NK, 
          MODIFICATION_ID, 
          DW_STARTDATE, 
          FISCALDATE, 
          DW_ENDDATE, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISDELETED, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          CHEQUE_FACT_FK, 
          DAYPART_DIM_FK, 
          EMPLOYEE_DIM_FK, 
          ITEM_FACT_FK, 
          LOCATION_DIM_FK, 
          MODIFIERGROUP_DIM_FK, 
          MODIFIER_DIM_FK, 
          IS_TRAINING, 
          CREATED_AT, 
          FISCAL_DATE, 
          OPENED_AT, 
          UPDATED_AT, 
          CHEQUESTATUS, 
          MODIFIER_GROUP, 
          MODIFIER, 
          MODIFIER_TYPE, 
          REVENUECENTERNAME, 
          ROUNDINGMETHOD, 
          CHEQUENUMBER, 
          PRICE 
) 
 SELECT   ITEMMODIFIER_DIM_NK  as   ITEMMODIFIER_DIM_NK,  
   MODIFICATION_ID  as   MODIFICATION_ID,  
   DW_STARTDATE  as   DW_STARTDATE,  
   FISCALDATE  as   FISCALDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISDELETED  as   DW_ISDELETED,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   CHEQUE_FACT_FK  as   CHEQUE_FACT_FK,  
   DAYPART_DIM_FK  as   DAYPART_DIM_FK,  
   EMPLOYEE_DIM_FK  as   EMPLOYEE_DIM_FK,  
   ITEM_FACT_FK  as   ITEM_FACT_FK,  
   LOCATION_DIM_FK  as   LOCATION_DIM_FK,  
   MODIFIERGROUP_DIM_FK  as   MODIFIERGROUP_DIM_FK,  
   MODIFIER_DIM_FK  as   MODIFIER_DIM_FK,  
   IS_TRAINING  as   IS_TRAINING,  
   CREATED_AT  as   CREATED_AT,  
   FISCAL_DATE  as   FISCAL_DATE,  
   OPENED_AT  as   OPENED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   CHEQUESTATUS  as   CHEQUESTATUS,  
   MODIFIER_GROUP  as   MODIFIER_GROUP,  
   MODIFIER  as   MODIFIER,  
   MODIFIER_TYPE  as   MODIFIER_TYPE,  
   REVENUECENTERNAME  as   REVENUECENTERNAME,  
   ROUNDINGMETHOD  as   ROUNDINGMETHOD,  
   CHEQUENUMBER  as   CHEQUENUMBER,  
   PRICE  as   PRICE 
  FROM DATAADMIN.ITEMMODIFIER_DIM
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''ITEMMODIFIER_DIM'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''ITEMMODIFIER_DIM'',''COUNT''));
END IF;
return table(errorCount_res); END';