CREATE OR REPLACE PROCEDURE "SP_STAGELOADEMPLOYMENTPERIOD_DIM"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.EMPLOYMENTPERIOD_DIM),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.EMPLOYMENTPERIOD_DIM(   
          EMPLOYMENTPERIOD_DIM_NK, 
          EMPLOYMENTPERIOD_ID, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          EMPLOYEE_DIM_FK, 
          JOBPOSITION_DIM_FK, 
          LOCATION_DIM_FK, 
          LOCATION_GROUP_DIM_FK, 
          CREATED_AT, 
          UPDATED_AT, 
          STARTED_AT, 
          ENDED_AT, 
          PAY_RATE_AMOUNT, 
          PAY_RATE_PER_SECOND 
) 
 SELECT   EMPLOYMENTPERIOD_DIM_NK  as   EMPLOYMENTPERIOD_DIM_NK,  
   EMPLOYMENTPERIOD_ID  as   EMPLOYMENTPERIOD_ID,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   EMPLOYEE_DIM_FK  as   EMPLOYEE_DIM_FK,  
   JOBPOSITION_DIM_FK  as   JOBPOSITION_DIM_FK,  
   LOCATION_DIM_FK  as   LOCATION_DIM_FK,  
   LOCATION_GROUP_DIM_FK  as   LOCATION_GROUP_DIM_FK,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   STARTED_AT  as   STARTED_AT,  
   ENDED_AT  as   ENDED_AT,  
   PAY_RATE_AMOUNT  as   PAY_RATE_AMOUNT,  
   PAY_RATE_PER_SECOND  as   PAY_RATE_PER_SECOND 
  FROM DATAADMIN.EMPLOYMENTPERIOD_DIM
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''EMPLOYMENTPERIOD_DIM'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''EMPLOYMENTPERIOD_DIM'',''COUNT''));
END IF;
return table(errorCount_res); END';