CREATE OR REPLACE PROCEDURE "SP_STAGELOADSTANDARDDISCOUNT_DIM"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.STANDARDDISCOUNT_DIM),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.STANDARDDISCOUNT_DIM(   
          STANDARDDISCOUNT_DIM_NK, 
          STANDARDDISCOUNTNAME, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          ORGANIZATION_DIM_FK, 
          IS_ENABLED, 
          IS_TAXABLE, 
          DO_AUTO_APPLY, 
          REQUIRE_APPROVAL, 
          CREATED_AT, 
          UPDATED_AT, 
          STANDARDDISCOUNTSHORTNAME, 
          RECEIPT_NAME, 
          OPEN_LIMIT, 
          DISCOUNTTYPE, 
          DISCOUNTAPPLICATION, 
          FIXED_VALUE, 
          MIN_CHECK_AMOUNT, 
          MAX_CHECK_AMOUNT 
) 
 SELECT   STANDARDDISCOUNT_DIM_NK  as   STANDARDDISCOUNT_DIM_NK,  
   STANDARDDISCOUNTNAME  as   STANDARDDISCOUNTNAME,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   ORGANIZATION_DIM_FK  as   ORGANIZATION_DIM_FK,  
   IS_ENABLED  as   IS_ENABLED,  
   IS_TAXABLE  as   IS_TAXABLE,  
   DO_AUTO_APPLY  as   DO_AUTO_APPLY,  
   REQUIRE_APPROVAL  as   REQUIRE_APPROVAL,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   STANDARDDISCOUNTSHORTNAME  as   STANDARDDISCOUNTSHORTNAME,  
   RECEIPT_NAME  as   RECEIPT_NAME,  
   OPEN_LIMIT  as   OPEN_LIMIT,  
   DISCOUNTTYPE  as   DISCOUNTTYPE,  
   DISCOUNTAPPLICATION  as   DISCOUNTAPPLICATION,  
   FIXED_VALUE  as   FIXED_VALUE,  
   MIN_CHECK_AMOUNT  as   MIN_CHECK_AMOUNT,  
   MAX_CHECK_AMOUNT  as   MAX_CHECK_AMOUNT 
  FROM DATAADMIN.STANDARDDISCOUNT_DIM
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''STANDARDDISCOUNT_DIM'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''STANDARDDISCOUNT_DIM'',''COUNT''));
END IF;
return table(errorCount_res); END';