CREATE OR REPLACE PROCEDURE "SP_STAGELOADSHIFTBREAK_FACT"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.SHIFTBREAK_FACT),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.SHIFTBREAK_FACT(   
          SHIFTBREAK_FACT_NK, 
          SHIFTBREAK, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          SHIFT_DIM_FK, 
          IS_BREAKCOMPLETE, 
          IS_ARCHIVED, 
          CREATED_AT, 
          UPDATED_AT, 
          START_AT, 
          ORIG_BEGIN_AT, 
          END_AT_INT, 
          END_AT, 
          ORIG_END_AT, 
          TIME_RANGE, 
          BREAK_SECONDS, 
          BREAK_MINUTES, 
          BREAK_HOURS, 
          BREAK_DAYS 
) 
 SELECT   SHIFTBREAK_FACT_NK  as   SHIFTBREAK_FACT_NK,  
   SHIFTBREAK  as   SHIFTBREAK,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   SHIFT_DIM_FK  as   SHIFT_DIM_FK,  
   IS_BREAKCOMPLETE  as   IS_BREAKCOMPLETE,  
   IS_ARCHIVED  as   IS_ARCHIVED,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   START_AT  as   START_AT,  
   ORIG_BEGIN_AT  as   ORIG_BEGIN_AT,  
   END_AT_INT  as   END_AT_INT,  
   END_AT  as   END_AT,  
   ORIG_END_AT  as   ORIG_END_AT,  
   TIME_RANGE  as   TIME_RANGE,  
   BREAK_SECONDS  as   BREAK_SECONDS,  
   BREAK_MINUTES  as   BREAK_MINUTES,  
   BREAK_HOURS  as   BREAK_HOURS,  
   BREAK_DAYS  as   BREAK_DAYS 
  FROM DATAADMIN.SHIFTBREAK_FACT
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''SHIFTBREAK_FACT'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''SHIFTBREAK_FACT'',''COUNT''));
END IF;
return table(errorCount_res); END';