CREATE OR REPLACE PROCEDURE "SP_STAGELOADGIFTCARDTRANSACTION_FACT"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.GIFTCARDTRANSACTION_FACT),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.GIFTCARDTRANSACTION_FACT(   
          GIFTCARDTRANSACTION_FACT_NK, 
          TRANSACTION, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          GIFTCARD_DIM_FK, 
          CHEQUE_FACT_FK, 
          LOCATION_DIM_FK, 
          ADJUSTED_BY_ID, 
          ADJUSTS_ID, 
          ADJUSTER, 
          IS_VOIDED, 
          IS_ADJUSTED, 
          CREATED_AT, 
          UPDATED_AT, 
          AUTH_GUID, 
          COMMAND, 
          CARD_ENTRY_METHOD, 
          CURRENCY_CODE, 
          AMOUNT, 
          ADJUSTED_AMOUNT, 
          TRANSACTION_AMOUNT, 
          TIP, 
          TOTAL, 
          BALANCE, 
          OPENING_BALANCE, 
          CLOSING_BALANCE 
) 
 SELECT   GIFTCARDTRANSACTION_FACT_NK  as   GIFTCARDTRANSACTION_FACT_NK,  
   TRANSACTION  as   TRANSACTION,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   GIFTCARD_DIM_FK  as   GIFTCARD_DIM_FK,  
   CHEQUE_FACT_FK  as   CHEQUE_FACT_FK,  
   LOCATION_DIM_FK  as   LOCATION_DIM_FK,  
   ADJUSTED_BY_ID  as   ADJUSTED_BY_ID,  
   ADJUSTS_ID  as   ADJUSTS_ID,  
   ADJUSTER  as   ADJUSTER,  
   IS_VOIDED  as   IS_VOIDED,  
   IS_ADJUSTED  as   IS_ADJUSTED,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   AUTH_GUID  as   AUTH_GUID,  
   COMMAND  as   COMMAND,  
   CARD_ENTRY_METHOD  as   CARD_ENTRY_METHOD,  
   CURRENCY_CODE  as   CURRENCY_CODE,  
   AMOUNT  as   AMOUNT,  
   ADJUSTED_AMOUNT  as   ADJUSTED_AMOUNT,  
   TRANSACTION_AMOUNT  as   TRANSACTION_AMOUNT,  
   TIP  as   TIP,  
   TOTAL  as   TOTAL,  
   BALANCE  as   BALANCE,  
   OPENING_BALANCE  as   OPENING_BALANCE,  
   CLOSING_BALANCE  as   CLOSING_BALANCE 
  FROM DATAADMIN.GIFTCARDTRANSACTION_FACT
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''GIFTCARDTRANSACTION_FACT'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''GIFTCARDTRANSACTION_FACT'',''COUNT''));
END IF;
return table(errorCount_res); END';