CREATE OR REPLACE PROCEDURE "SP_STAGELOADSURCHARGE_DIM"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.SURCHARGE_DIM),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.SURCHARGE_DIM(   
          SURCHARGE_DIM_NK, 
          SURCHARGE, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          ORGANIZATION_DIM_FK, 
          IS_ARCHIVED, 
          IS_ENABLED, 
          IS_PRINT_ON_RECEIPT, 
          IS_TAXABLE, 
          IS_GRATUITY, 
          CREATED_AT, 
          UPDATED_AT, 
          DESCRIPTION, 
          POS_NAME, 
          RECEIPT_DISPLAY_NAME, 
          TYPE, 
          MIN_GUESTS, 
          MIN_CHECK_AMOUNT, 
          FIXED_VALUE 
) 
 SELECT   SURCHARGE_DIM_NK  as   SURCHARGE_DIM_NK,  
   SURCHARGE  as   SURCHARGE,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   ORGANIZATION_DIM_FK  as   ORGANIZATION_DIM_FK,  
   IS_ARCHIVED  as   IS_ARCHIVED,  
   IS_ENABLED  as   IS_ENABLED,  
   IS_PRINT_ON_RECEIPT  as   IS_PRINT_ON_RECEIPT,  
   IS_TAXABLE  as   IS_TAXABLE,  
   IS_GRATUITY  as   IS_GRATUITY,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   DESCRIPTION  as   DESCRIPTION,  
   POS_NAME  as   POS_NAME,  
   RECEIPT_DISPLAY_NAME  as   RECEIPT_DISPLAY_NAME,  
   TYPE  as   TYPE,  
   MIN_GUESTS  as   MIN_GUESTS,  
   MIN_CHECK_AMOUNT  as   MIN_CHECK_AMOUNT,  
   FIXED_VALUE  as   FIXED_VALUE 
  FROM DATAADMIN.SURCHARGE_DIM
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''SURCHARGE_DIM'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''SURCHARGE_DIM'',''COUNT''));
END IF;
return table(errorCount_res); END';