CREATE OR REPLACE PROCEDURE "SP_STAGELOADCCTRANSACTION_FACT"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.CCTRANSACTION_FACT),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.CCTRANSACTION_FACT(   
          CCTRANSACTION_FACT_NK, 
          TRANSACTION_NUMBER, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          BATCH_DIM_FK, 
          LOCATION_DIM_FK, 
          EMPLOYEE_DIM_FK, 
          PAYMENTMETHOD_DIM_FK, 
          CHEQUE_FACT_FK, 
          ISCARDPRESENT, 
          ISFIRSTTRANSACTION, 
          FISCAL_DAY, 
          AUTH_TRAN_GMT, 
          CREATED_AT, 
          UPDATED_AT, 
          AUTH_TRAN_ID, 
          BATCH_ID, 
          AUTH_BRIC, 
          CARDHOLDER_LOCATION, 
          CARD_ENTRY_METHOD, 
          BATCH_NUMBER, 
          AUTHORIZATION, 
          AUTHORIZATION_CODE, 
          APPROVAL, 
          POS_TERMINAL_ID, 
          MASKED_CC_NUMBER, 
          CARDHOLDER_NAME, 
          CARD_TYPE, 
          CARD_TYPE_RAW, 
          REFERENCE_NUMBER, 
          COMMAND, 
          STATUS, 
          AUTHAMOUNTREQUESTED, 
          AUTH_AMOUNT, 
          TOTAL_INCREMENT, 
          TIP_INCREMENT, 
          TOTAL, 
          TIP 
) 
 SELECT   CCTRANSACTION_FACT_NK  as   CCTRANSACTION_FACT_NK,  
   TRANSACTION_NUMBER  as   TRANSACTION_NUMBER,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   BATCH_DIM_FK  as   BATCH_DIM_FK,  
   LOCATION_DIM_FK  as   LOCATION_DIM_FK,  
   EMPLOYEE_DIM_FK  as   EMPLOYEE_DIM_FK,  
   PAYMENTMETHOD_DIM_FK  as   PAYMENTMETHOD_DIM_FK,  
   CHEQUE_FACT_FK  as   CHEQUE_FACT_FK,  
   ISCARDPRESENT  as   ISCARDPRESENT,  
   ISFIRSTTRANSACTION  as   ISFIRSTTRANSACTION,  
   FISCAL_DAY  as   FISCAL_DAY,  
   AUTH_TRAN_GMT  as   AUTH_TRAN_GMT,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   AUTH_TRAN_ID  as   AUTH_TRAN_ID,  
   BATCH_ID  as   BATCH_ID,  
   AUTH_BRIC  as   AUTH_BRIC,  
   CARDHOLDER_LOCATION  as   CARDHOLDER_LOCATION,  
   CARD_ENTRY_METHOD  as   CARD_ENTRY_METHOD,  
   BATCH_NUMBER  as   BATCH_NUMBER,  
   AUTHORIZATION  as   AUTHORIZATION,  
   AUTHORIZATION_CODE  as   AUTHORIZATION_CODE,  
   APPROVAL  as   APPROVAL,  
   POS_TERMINAL_ID  as   POS_TERMINAL_ID,  
   MASKED_CC_NUMBER  as   MASKED_CC_NUMBER,  
   CARDHOLDER_NAME  as   CARDHOLDER_NAME,  
   CARD_TYPE  as   CARD_TYPE,  
   CARD_TYPE_RAW  as   CARD_TYPE_RAW,  
   REFERENCE_NUMBER  as   REFERENCE_NUMBER,  
   COMMAND  as   COMMAND,  
   STATUS  as   STATUS,  
   AUTHAMOUNTREQUESTED  as   AUTHAMOUNTREQUESTED,  
   AUTH_AMOUNT  as   AUTH_AMOUNT,  
   TOTAL_INCREMENT  as   TOTAL_INCREMENT,  
   TIP_INCREMENT  as   TIP_INCREMENT,  
   TOTAL  as   TOTAL,  
   TIP  as   TIP 
  FROM DATAADMIN.CCTRANSACTION_FACT
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''CCTRANSACTION_FACT'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''CCTRANSACTION_FACT'',''COUNT''));
END IF;
return table(errorCount_res); END';