CREATE OR REPLACE PROCEDURE "SP_STAGELOADERRORDWDATE_DIM"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.ERRORDWDATE_DIM),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.ERRORDWDATE_DIM(   
          ERRORDWDATE_DIM_NK, 
          REPORTCATEGORY, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_ISCURRENTROW, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          ORGANIZATION_DIM_FK, 
          CREATED_AT, 
          MODIFIED_AT, 
          TESTERROR_AT, 
          TESTERROR_ID, 
          IS_BOOLEANTEST, 
          ERROR_VARIANT, 
          TEST_ID, 
          TEST_DECIMAL_TRUE, 
          TEST_NUMERIC_TRUE, 
          TEST_AMOUNT_FALSE, 
          TEST_BOOLEAN_TRUE, 
          V, 
          VTYPE_INT, 
          VTYPE_DEC, 
          VTYPE_STRING, 
          VTYPE_BOOLEAN, 
          VTYPE_DATE, 
          IS_NAMEBOOLEANERROR, 
          NAMEBOOLEANERROR_IS, 
          NAMENUMBRANERROR_COUNT 
) 
 SELECT   ERRORDWDATE_DIM_NK  as   ERRORDWDATE_DIM_NK,  
   REPORTCATEGORY  as   REPORTCATEGORY,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   ORGANIZATION_DIM_FK  as   ORGANIZATION_DIM_FK,  
   CREATED_AT  as   CREATED_AT,  
   MODIFIED_AT  as   MODIFIED_AT,  
   TESTERROR_AT  as   TESTERROR_AT,  
   TESTERROR_ID  as   TESTERROR_ID,  
   IS_BOOLEANTEST  as   IS_BOOLEANTEST,  
   ERROR_VARIANT  as   ERROR_VARIANT,  
   TEST_ID  as   TEST_ID,  
   TEST_DECIMAL_TRUE  as   TEST_DECIMAL_TRUE,  
   TEST_NUMERIC_TRUE  as   TEST_NUMERIC_TRUE,  
   TEST_AMOUNT_FALSE  as   TEST_AMOUNT_FALSE,  
   TEST_BOOLEAN_TRUE  as   TEST_BOOLEAN_TRUE,  
   V  as   V,  
   VTYPE_INT  as   VTYPE_INT,  
   VTYPE_DEC  as   VTYPE_DEC,  
   VTYPE_STRING  as   VTYPE_STRING,  
   VTYPE_BOOLEAN  as   VTYPE_BOOLEAN,  
   VTYPE_DATE  as   VTYPE_DATE,  
   IS_NAMEBOOLEANERROR  as   IS_NAMEBOOLEANERROR,  
   NAMEBOOLEANERROR_IS  as   NAMEBOOLEANERROR_IS,  
   NAMENUMBRANERROR_COUNT  as   NAMENUMBRANERROR_COUNT 
  FROM DATAADMIN.ERRORDWDATE_DIM
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''ERRORDWDATE_DIM'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''ERRORDWDATE_DIM'',''COUNT''));
END IF;
return table(errorCount_res); END';