CREATE OR REPLACE PROCEDURE "SP_STAGELOADORGANIZATION_DIM"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.ORGANIZATION_DIM),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.ORGANIZATION_DIM(   
          ORGANIZATION_DIM_NK, 
          ORGANIZATION, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          DO_AUTO_END_SHIFTS, 
          FISCAL_DAY_START, 
          START_OF_PAYROLL_WEEK_INT, 
          START_OF_BIZ_WEEK_INT, 
          CREATED_AT, 
          UPDATED_AT, 
          STATUS, 
          VERSION, 
          SERVICE_LEVEL, 
          DEFAULT_CURRENCY, 
          SUPPORTED_CURRENCIES 
) 
 SELECT   ORGANIZATION_DIM_NK  as   ORGANIZATION_DIM_NK,  
   ORGANIZATION  as   ORGANIZATION,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   DO_AUTO_END_SHIFTS  as   DO_AUTO_END_SHIFTS,  
   FISCAL_DAY_START  as   FISCAL_DAY_START,  
   START_OF_PAYROLL_WEEK_INT  as   START_OF_PAYROLL_WEEK_INT,  
   START_OF_BIZ_WEEK_INT  as   START_OF_BIZ_WEEK_INT,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   STATUS  as   STATUS,  
   VERSION  as   VERSION,  
   SERVICE_LEVEL  as   SERVICE_LEVEL,  
   DEFAULT_CURRENCY  as   DEFAULT_CURRENCY,  
   SUPPORTED_CURRENCIES  as   SUPPORTED_CURRENCIES 
  FROM DATAADMIN.ORGANIZATION_DIM
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''ORGANIZATION_DIM'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''ORGANIZATION_DIM'',''COUNT''));
END IF;
return table(errorCount_res); END';