CREATE OR REPLACE PROCEDURE "SP_STAGELOADGIFTCARDACTIVITY_FACT"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.GIFTCARDACTIVITY_FACT),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.GIFTCARDACTIVITY_FACT(   
          GIFTCARDACTIVITY_FACT_NK, 
          GIFTCARD, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          ACCOUNT_DIM_FK, 
          CHEQUE_FACT_FK, 
          DAYPART_DIM_FK, 
          EMPLOYEE_DIM_FK_AS_CREATOR, 
          LOCATION_DIM_FK, 
          MERCHANT_DIM_FK, 
          ORDERTYPE_DIM_FK, 
          REVENUECENTER_DIM_FK, 
          STATUSREASON_DIM_FK, 
          IS_RELOAD, 
          IS_TRAINING, 
          CREATED_AT, 
          UPDATED_AT, 
          OPENED_AT, 
          FISCALDATE, 
          AUTHGUIDID, 
          CHEQUENUMBER, 
          CURRENCY_ID, 
          FLOORPLAN_ID, 
          REVENUECENTERNAME, 
          STATUS, 
          STATUSREASON, 
          TABLENAME, 
          PARTYSIZE, 
          AMOUNT 
) 
 SELECT   GIFTCARDACTIVITY_FACT_NK  as   GIFTCARDACTIVITY_FACT_NK,  
   GIFTCARD  as   GIFTCARD,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   ACCOUNT_DIM_FK  as   ACCOUNT_DIM_FK,  
   CHEQUE_FACT_FK  as   CHEQUE_FACT_FK,  
   DAYPART_DIM_FK  as   DAYPART_DIM_FK,  
   EMPLOYEE_DIM_FK_AS_CREATOR  as   EMPLOYEE_DIM_FK_AS_CREATOR,  
   LOCATION_DIM_FK  as   LOCATION_DIM_FK,  
   MERCHANT_DIM_FK  as   MERCHANT_DIM_FK,  
   ORDERTYPE_DIM_FK  as   ORDERTYPE_DIM_FK,  
   REVENUECENTER_DIM_FK  as   REVENUECENTER_DIM_FK,  
   STATUSREASON_DIM_FK  as   STATUSREASON_DIM_FK,  
   IS_RELOAD  as   IS_RELOAD,  
   IS_TRAINING  as   IS_TRAINING,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   OPENED_AT  as   OPENED_AT,  
   FISCALDATE  as   FISCALDATE,  
   AUTHGUIDID  as   AUTHGUIDID,  
   CHEQUENUMBER  as   CHEQUENUMBER,  
   CURRENCY_ID  as   CURRENCY_ID,  
   FLOORPLAN_ID  as   FLOORPLAN_ID,  
   REVENUECENTERNAME  as   REVENUECENTERNAME,  
   STATUS  as   STATUS,  
   STATUSREASON  as   STATUSREASON,  
   TABLENAME  as   TABLENAME,  
   PARTYSIZE  as   PARTYSIZE,  
   AMOUNT  as   AMOUNT 
  FROM DATAADMIN.GIFTCARDACTIVITY_FACT
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''GIFTCARDACTIVITY_FACT'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''GIFTCARDACTIVITY_FACT'',''COUNT''));
END IF;
return table(errorCount_res); END';