CREATE OR REPLACE PROCEDURE "SP_STAGELOADACTIVITY_FACT"("VALIDATE_DATE" BOOLEAN)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE res resultset;
      --validate_date boolean := TRUE;
      errorCount_res resultset;
      highwater int := IFNULL((SELECT MAX(MTLN_CDC_SEQUENCE_NUMBER) FROM DATAWAREHOUSE_TEMP.ACTIVITY_FACT),0);
  BEGIN
    res := (
       INSERT INTO DATAWAREHOUSE_TEMP.ACTIVITY_FACT(   
          ACTIVITY_FACT_NK, 
          ACTIVITY, 
          DW_STARTDATE, 
          DW_ENDDATE, 
          DW_ISDELETED, 
          DW_RANGESTART, 
          DW_RANGEEND, 
          DW_ISCURRENTROW, 
          MTLN_CDC_LAST_CHANGE_TYPE, 
          MTLN_CDC_LAST_COMMIT_TIMESTAMP, 
          MTLN_CDC_SEQUENCE_NUMBER, 
          MTLN_CDC_LOAD_BATCH_ID, 
          MTLN_CDC_LOAD_TIMESTAMP, 
          MTLN_CDC_PROCESSED_DATE_HOUR, 
          MTLN_CDC_SRC_VERSION, 
          MTLN_CDC_FILENAME, 
          MTLN_CDC_FILEPATH, 
          MTLN_CDC_SRC_DATABASE, 
          MTLN_CDC_SRC_SCHEMA, 
          MTLN_CDC_SRC_TABLE, 
          VOIDSUMMARY_FACT_FK, 
          CHEQUE_FACT_FK, 
          DISCOUNT_FACT_FK, 
          EMPLOYEE_DIM_FK, 
          EMPLOYEE_DIM_FK_AS_PERFORMING_EMPLOYEE, 
          EMPLOYEE_DIM_FK_AS_APPROVING_EMPLOYEE, 
          ITEM_FACT_FK, 
          LOCATION_DIM_FK, 
          MENUITEM_DIM_FK, 
          IS_DISCOUNT, 
          IS_TRAINING, 
          IS_VOID, 
          IS_VOID_ITEM, 
          CREATED_AT, 
          UPDATED_AT, 
          PERFORMED_AT, 
          TABLENAME, 
          PERFORMEDBYUSERUUID, 
          MENUITEMNAME, 
          MENUITEMID, 
          TYPE, 
          ITEM_ID, 
          OVERRIDE, 
          LEVEL, 
          REASON, 
          PRICE 
) 
 SELECT   ACTIVITY_FACT_NK  as   ACTIVITY_FACT_NK,  
   ACTIVITY  as   ACTIVITY,  
   DW_STARTDATE  as   DW_STARTDATE,  
   DW_ENDDATE  as   DW_ENDDATE,  
   DW_ISDELETED  as   DW_ISDELETED,  
   :highwater  as   DW_RANGESTART,  
   MAX(MTLN_CDC_SEQUENCE_NUMBER) OVER(PARTITION BY 1)  as   DW_RANGEEND,  
   DW_ISCURRENTROW  as   DW_ISCURRENTROW,  
   MTLN_CDC_LAST_CHANGE_TYPE  as   MTLN_CDC_LAST_CHANGE_TYPE,  
   MTLN_CDC_LAST_COMMIT_TIMESTAMP  as   MTLN_CDC_LAST_COMMIT_TIMESTAMP,  
   MTLN_CDC_SEQUENCE_NUMBER  as   MTLN_CDC_SEQUENCE_NUMBER,  
   MTLN_CDC_LOAD_BATCH_ID  as   MTLN_CDC_LOAD_BATCH_ID,  
   MTLN_CDC_LOAD_TIMESTAMP  as   MTLN_CDC_LOAD_TIMESTAMP,  
   MTLN_CDC_PROCESSED_DATE_HOUR  as   MTLN_CDC_PROCESSED_DATE_HOUR,  
   MTLN_CDC_SRC_VERSION  as   MTLN_CDC_SRC_VERSION,  
   MTLN_CDC_FILENAME  as   MTLN_CDC_FILENAME,  
   MTLN_CDC_FILEPATH  as   MTLN_CDC_FILEPATH,  
   MTLN_CDC_SRC_DATABASE  as   MTLN_CDC_SRC_DATABASE,  
   MTLN_CDC_SRC_SCHEMA  as   MTLN_CDC_SRC_SCHEMA,  
   MTLN_CDC_SRC_TABLE  as   MTLN_CDC_SRC_TABLE,  
   VOIDSUMMARY_FACT_FK  as   VOIDSUMMARY_FACT_FK,  
   CHEQUE_FACT_FK  as   CHEQUE_FACT_FK,  
   DISCOUNT_FACT_FK  as   DISCOUNT_FACT_FK,  
   EMPLOYEE_DIM_FK  as   EMPLOYEE_DIM_FK,  
   EMPLOYEE_DIM_FK_AS_PERFORMING_EMPLOYEE  as   EMPLOYEE_DIM_FK_AS_PERFORMING_EMPLOYEE,  
   EMPLOYEE_DIM_FK_AS_APPROVING_EMPLOYEE  as   EMPLOYEE_DIM_FK_AS_APPROVING_EMPLOYEE,  
   ITEM_FACT_FK  as   ITEM_FACT_FK,  
   LOCATION_DIM_FK  as   LOCATION_DIM_FK,  
   MENUITEM_DIM_FK  as   MENUITEM_DIM_FK,  
   IS_DISCOUNT  as   IS_DISCOUNT,  
   IS_TRAINING  as   IS_TRAINING,  
   IS_VOID  as   IS_VOID,  
   IS_VOID_ITEM  as   IS_VOID_ITEM,  
   CREATED_AT  as   CREATED_AT,  
   UPDATED_AT  as   UPDATED_AT,  
   PERFORMED_AT  as   PERFORMED_AT,  
   TABLENAME  as   TABLENAME,  
   PERFORMEDBYUSERUUID  as   PERFORMEDBYUSERUUID,  
   MENUITEMNAME  as   MENUITEMNAME,  
   MENUITEMID  as   MENUITEMID,  
   TYPE  as   TYPE,  
   ITEM_ID  as   ITEM_ID,  
   OVERRIDE  as   OVERRIDE,  
   LEVEL  as   LEVEL,  
   REASON  as   REASON,  
   PRICE  as   PRICE 
  FROM DATAADMIN.ACTIVITY_FACT
     WHERE MTLN_CDC_SEQUENCE_NUMBER > :highwater);

 
 --======================================================================================================================== 

 
--========================================================================================================================
CALL SP_UpdateDWTable( ''DATASTAGE'', ''ACTIVITY_FACT'');
IF (validate_date = TRUE)  THEN  errorCount_res := (CALL DATAADMIN.SP_ValidateDWDates(''p'',''ACTIVITY_FACT'',''COUNT''));
END IF;
return table(errorCount_res); END';