CREATE OR REPLACE PROCEDURE DEV_HOSPENG_REPORTING.GIT_TEST.SP_ADD_DISCOUNT()
RETURN STRING
LANGUAGE SQL
AS
$$
BEGIN
    UPDATE DEV_HOSPENG_REPORTING.GIT_TEST.PRODUCTS
    SET PRICE = PRICE * 0.9
    WHERE PRICE > 100;

    RETURN 'DISCOUNT APPLIED.';
END;
$$;