create or replace view ERRORDWDATE_DIM(
	ERRORDWDATE_DIM_NK,
	REPORTCATEGORY,
	DW_STARTDATE,
	DW_ENDDATE,
	DW_ISDELETED,
	DW_ISCURRENTROW,
	MTLN_CDC_LAST_CHANGE_TYPE,
	MTLN_CDC_LAST_COMMIT_TIMESTAMP,
	MTLN_CDC_SEQUENCE_NUMBER,
	MTLN_CDC_LOAD_BATCH_ID,
	MTLN_CDC_LOAD_TIMESTAMP,
	MTLN_CDC_PROCESSED_DATE_HOUR,
	MTLN_CDC_SRC_VERSION,
	MTLN_CDC_FILENAME,
	MTLN_CDC_FILEPATH,
	MTLN_CDC_SRC_SCHEMA,
	MTLN_CDC_SRC_TABLE,
	ORGANIZATION_DIM_FK,
	CREATED_AT,
	MODIFIED_AT,
	TESTERROR_AT,
	TESTERROR_ID,
	IS_BOOLEANTEST,
	ERROR_VARIANT,
	TEST_ID,
	TEST_DECIMAL_TRUE,
	TEST_NUMERIC_TRUE,
	TEST_AMOUNT_FALSE,
	TEST_BOOLEAN_TRUE,
	V,
	VTYPE_INT,
	VTYPE_DEC,
	VTYPE_STRING,
	VTYPE_BOOLEAN,
	VTYPE_DATE,
	IS_NAMEBOOLEANERROR,
	NAMEBOOLEANERROR_IS,
	NAMENUMBRANERROR_COUNT
) as

SELECT 
REPORTCATEGORY_DIM_NK  as ERRORDWDATE_DIM_NK, REPORTCATeGORY, DW_STARTDATE, DW_ENDDATE, DW_ISDELETED, DW_ISCURRENTROW, MTLN_CDC_LAST_CHANGE_TYPE, MTLN_CDC_LAST_COMMIT_TIMESTAMP, MTLN_CDC_SEQUENCE_NUMBER, MTLN_CDC_LOAD_BATCH_ID, MTLN_CDC_LOAD_TIMESTAMP, MTLN_CDC_PROCESSED_DATE_HOUR, MTLN_CDC_SRC_VERSION, MTLN_CDC_FILENAME, MTLN_CDC_FILEPATH, MTLN_CDC_SRC_SCHEMA, MTLN_CDC_SRC_TABLE, ORGANIZATION_DIM_FK, CREATED_AT, UPDATED_AT AS MODIFIED_AT
, '1234' AS TESTERROR_AT
, '1234' AS TESTERROR_id
,'true' AS IS_BOOLEANtest
,CAST(233 AS VARIANT) as ERROR_VARIANT
,'233' as test_id
,'123.777' AS test_decimal_true
,'444' AS test_numeric_true
,'444.45' AS TEST_AMOUNT_false
,'true' as test_boolean_true
,'123.777' AS v

,CAST(456 as VARIANT) AS VType_int
,CAST(1234.4567 as VARIANT) AS VType_dec
,CAST('here is text' as VARIANT) AS VType_string
,CAST(true as VARIANT) AS VType_boolean
,CAST('2022-08-26T20:01:09.134279Z' as VARIANT) AS VType_date

,CAST ('BST' AS VARCHAR) AS IS_NAMEBOOLEANERROR
,CAST ('XXX' AS VARCHAR) AS NAMEBOOLEANERROR_IS
,CAST ('2245' AS VARCHAR) AS NAMENUMBRANERROR_COUNT


FROM REPORTCATEGORY_DIM

UNION

SELECT 
REPORTCATEGORY_DIM_NK, REPORTCATeGORY, DW_STARTDATE, DW_ENDDATE, DW_ISDELETED, DW_ISCURRENTROW, MTLN_CDC_LAST_CHANGE_TYPE, MTLN_CDC_LAST_COMMIT_TIMESTAMP, MTLN_CDC_SEQUENCE_NUMBER, MTLN_CDC_LOAD_BATCH_ID, MTLN_CDC_LOAD_TIMESTAMP, MTLN_CDC_PROCESSED_DATE_HOUR, MTLN_CDC_SRC_VERSION, MTLN_CDC_FILENAME, MTLN_CDC_FILEPATH, MTLN_CDC_SRC_SCHEMA, MTLN_CDC_SRC_TABLE, ORGANIZATION_DIM_FK, CREATED_AT, UPDATED_AT
, '1234' AS TESTERROR_AT
, '1234' AS TESTERROR_id
,'true' AS IS_BOOLEANtest
,CAST('233' AS VARIANT) as ERROR_VARIANT
,'233' as test_id
,'123.777' AS test_decimal_true
,'444' AS test_numeric_true
,'444 first street' AS TEST_AMOUNT_false
,'false' as test_boolean_true
,'123.777' AS v

,CAST(456 as VARIANT) AS VType_int
,CAST(1234.4567 as VARIANT) AS VType_dec
,CAST('here is text' as VARIANT) AS VType_string
,CAST(false as VARIANT) AS VType_boolean
,CAST('2022-08-26T20:01:09.134279Z' as VARIANT) AS VType_date

,CAST ('TRUE' AS VARCHAR) AS IS_NAMEBOOLEANERROR
,CAST ('TRUE' AS VARCHAR) AS NAMEBOOLEANERROR_IS
,CAST ('2245' AS VARCHAR) AS NAMENUMBRANERROR_COUNT

FROM REPORTCATEGORY_DIM
;